//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspenlaub.Net.GitHub.CSharp.Nuclide.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspenlaub.Net.GitHub.CSharp.Nuclide.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch &apos;{0}&apos; does not produce packages.
        /// </summary>
        internal static string BranchDoesNotHavePackages {
            get {
                return ResourceManager.GetString("BranchDoesNotHavePackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking project ID against solution ID.
        /// </summary>
        internal static string CheckingProjectVsSolution {
            get {
                return ResourceManager.GetString("CheckingProjectVsSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking remote package tag.
        /// </summary>
        internal static string CheckingRemotePackageTag {
            get {
                return ResourceManager.GetString("CheckingRemotePackageTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not access nuget feed &apos;{0}&apos;.
        /// </summary>
        internal static string CouldNotAccessNugetFeed {
            get {
                return ResourceManager.GetString("CouldNotAccessNugetFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not deserialize object from file &quot;{0}&quot;.
        /// </summary>
        internal static string CouldNotDeserializeFromFile {
            get {
                return ResourceManager.GetString("CouldNotDeserializeFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read target framework from &quot;{0}&quot;.
        /// </summary>
        internal static string ErrorReadingTargetFramework {
            get {
                return ResourceManager.GetString("ErrorReadingTargetFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; not found.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder &quot;{0}&quot; is obsolete.
        /// </summary>
        internal static string FolderIsObsolete {
            get {
                return ResourceManager.GetString("FolderIsObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found local package {0}.
        /// </summary>
        internal static string FoundLocalPackage {
            get {
                return ResourceManager.GetString("FoundLocalPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found remote package {0}.
        /// </summary>
        internal static string FoundRemotePackage {
            get {
                return ResourceManager.GetString("FoundRemotePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head tip sha {0} has not yet been pushed.
        /// </summary>
        internal static string HeadTipShaNotPushed {
            get {
                return ResourceManager.GetString("HeadTipShaNotPushed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifying feed URL.
        /// </summary>
        internal static string IdentifyingFeedUrl {
            get {
                return ResourceManager.GetString("IdentifyingFeedUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifying nuget feed.
        /// </summary>
        internal static string IdentifyingNugetFeed {
            get {
                return ResourceManager.GetString("IdentifyingNugetFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete &apos;DeveloperSettings&apos;. Please update &quot;{0}&quot; in your SecretRepository.
        /// </summary>
        internal static string IncompleteDeveloperSettings {
            get {
                return ResourceManager.GetString("IncompleteDeveloperSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no valid XML in &quot;{0}&quot;.
        /// </summary>
        internal static string InvalidXmlFile {
            get {
                return ResourceManager.GetString("InvalidXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading nuget feeds.
        /// </summary>
        internal static string LoadingNugetFeeds {
            get {
                return ResourceManager.GetString("LoadingNugetFeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading project.
        /// </summary>
        internal static string LoadingProject {
            get {
                return ResourceManager.GetString("LoadingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading pushed head tip shas.
        /// </summary>
        internal static string LoadingPushedHeadTipShas {
            get {
                return ResourceManager.GetString("LoadingPushedHeadTipShas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing secret branches with packages.
        /// </summary>
        internal static string MissingBranchesWithPackagesSettings {
            get {
                return ResourceManager.GetString("MissingBranchesWithPackagesSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing &apos;DeveloperSettings&apos; secret. Open &quot;{0}&quot; in SecretSamples, modify it and save it in SecretRepository.
        /// </summary>
        internal static string MissingDeveloperSettings {
            get {
                return ResourceManager.GetString("MissingDeveloperSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one element was not found in &apos;{0}&apos;.
        /// </summary>
        internal static string MissingElementInProjectFile {
            get {
                return ResourceManager.GetString("MissingElementInProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one metadata element was not found in &apos;{0}&apos;.
        /// </summary>
        internal static string MissingMetaDataElementInProjectFile {
            get {
                return ResourceManager.GetString("MissingMetaDataElementInProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing root namespace.
        /// </summary>
        internal static string MissingRootNamespace {
            get {
                return ResourceManager.GetString("MissingRootNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing target framework.
        /// </summary>
        internal static string MissingTargetFramework {
            get {
                return ResourceManager.GetString("MissingTargetFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No apikey was found for this source.
        /// </summary>
        internal static string NoApiKeyFound {
            get {
                return ResourceManager.GetString("NoApiKeyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder &quot;{0}&quot; does not contain any packages.
        /// </summary>
        internal static string NoPackageFilesFound {
            get {
                return ResourceManager.GetString("NoPackageFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pushed head tip shas found in: {0}.
        /// </summary>
        internal static string NoPushedHeadTipShasFound {
            get {
                return ResourceManager.GetString("NoPushedHeadTipShasFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; has been updated.
        /// </summary>
        internal static string NuSpecFileUpdated {
            get {
                return ResourceManager.GetString("NuSpecFileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder &quot;{0}&quot; is obsolete and has been deleted.
        /// </summary>
        internal static string ObsoleteFolderDeleted {
            get {
                return ResourceManager.GetString("ObsoleteFolderDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote package is already tagged with the head tip sha.
        /// </summary>
        internal static string PackageAlreadyTaggedWithHeadTipSha {
            get {
                return ResourceManager.GetString("PackageAlreadyTaggedWithHeadTipSha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package needs to be pushed.
        /// </summary>
        internal static string PackageNeedsToBePushed {
            get {
                return ResourceManager.GetString("PackageNeedsToBePushed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cake add-in package &quot;{0}&quot; is not pinned to version &quot;{1}&quot;.
        /// </summary>
        internal static string PackageNotPinnedToVersion {
            get {
                return ResourceManager.GetString("PackageNotPinnedToVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; requests package &apos;{1}&apos; with version {2}, but another one version {3}.
        /// </summary>
        internal static string PackageVersionClashDueToFile {
            get {
                return ResourceManager.GetString("PackageVersionClashDueToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; refers to a package without an ID.
        /// </summary>
        internal static string PackageWithoutId {
            get {
                return ResourceManager.GetString("PackageWithoutId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; refers to package &apos;{1}&apos; without a version number.
        /// </summary>
        internal static string PackageWithoutVersion {
            get {
                return ResourceManager.GetString("PackageWithoutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; refers to a specific version of package &apos;{1}&apos;.
        /// </summary>
        internal static string PackageWithVersion {
            get {
                return ResourceManager.GetString("PackageWithVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no project file &quot;{0}&quot;.
        /// </summary>
        internal static string ProjectFileNotFound {
            get {
                return ResourceManager.GetString("ProjectFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote package version number is higher or equal to the version number of the local package.
        /// </summary>
        internal static string RemotePackageHasHigherOrEqualVersion {
            get {
                return ResourceManager.GetString("RemotePackageHasHigherOrEqualVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching local package.
        /// </summary>
        internal static string SearchingLocalPackage {
            get {
                return ResourceManager.GetString("SearchingLocalPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching remote package.
        /// </summary>
        internal static string SearchingRemotePackage {
            get {
                return ResourceManager.GetString("SearchingRemotePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote package tags are: &quot;{0}&quot;.
        /// </summary>
        internal static string TagsAre {
            get {
                return ResourceManager.GetString("TagsAre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top level namespace &apos;{0}&apos; does not contain any dot (&apos;.&apos;).
        /// </summary>
        internal static string TopLevelNamespaceLacksADot {
            get {
                return ResourceManager.GetString("TopLevelNamespaceLacksADot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown nuget feed &apos;{0}&apos;, please add to &quot;{1}&quot; in your SecretRepository.
        /// </summary>
        internal static string UnknownNugetFeed {
            get {
                return ResourceManager.GetString("UnknownNugetFeed", resourceCulture);
            }
        }
    }
}
